import mongoose from "mongoose";
const userSchema = new mongoose.Schema({
    firstname:{
        type:String,
        required:true,
        trim:true
    },
    lastname:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true,
        unique:true
    },
    password:{
        type:String,
        required:true,
        trim:true
    },
    bio:{
        type:String
    },
    avatar:{
        type:String,
        default:""
    },
    userProfile:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"UserProfile"
    },
    links:[{
        type:String
    }],
    blogs:[{
        title:{
            type:String
        },
        description:{
            type:String
        },
        body:{
            type:String
        },
        multimedia:[{
            type:String
        }],
        like:{
            type:Number
        },
        comments:[{
            type:String
        }],
        links:[{
            type:String
        }]
    }]
},{timestamps:true})
export const User = mongoose.model("User",userSchema)